# Generated by Django 2.0.13 on 2019-04-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('dateTime', models.DateTimeField()),
                ('times', models.IntegerField()),
                ('effective', models.BooleanField()),
            ],
            options={
                'db_table': 'loginTimes',
                'ordering': ['id'],
            },
        ),
    ]
